#!/usr/bin/env ruby

DEPENDENCIES = 
  "aclocal",
  "autoconf",
  "automake",
  "autoreconf"

COMMANDS =
  "aclocal",
  "autoconf",
  "automake --add-missing",
  "autoreconf",
  "automake",
  "./configure"

# ASCII text coloring
def heading(text)
  "\033[1;37m" + text + "\033[0m"
end

def purpify(text)
  "\033[0;35m" + text + "\033[0m"
end

def greenify(text)
  "\033[0;32m" + text + "\033[0m"
end

def redify(text)
  "\033[0;31m" + text + "\033[0m"
end

puts heading "Checking Autotools Dependencies..."

# Check dependencies
dependency_header = greenify "Checking: "
missing_deps = []

DEPENDENCIES.each do |dependency|
  puts dependency_header + purpify(dependency)
  unless system("which #{dependency}", :out => "/dev/null")
    missing_deps << dependency
  end
end

unless missing_deps.empty?
  puts heading "build-env failed..."
  missing_deps.each do |missing|
    puts redify "Missing: #{missing}"
  end
  puts redify "Install the missing dependencies and run again."
  exit 1
end

puts heading "Building Environment..."

command_header = greenify "Running: "

# Execute build commands
COMMANDS.each do |command|
  puts command_header + purpify(command)
  system(command)
end

puts greenify "Your environment setup is complete. Run `make` to build your project."
